def get_short_name(teamname):
    if teamname == "Mumbai Indians":return "MI"
    if teamname == "Chennai Super Kings":return "CSK"
    if teamname == "Royal Challengers Bengaluru":return "RCB"
    if teamname == "Delhi Capitals":return "DC"
    if teamname == "Sunrisers Hyderabad":return "SRH"
    if teamname == "Rajasthan Royals":return "RR"
    if teamname == "Gujarat Titans":return "GT"
    if teamname == "Kolkata Knight Riders":return "KKR"
    if teamname == "Punjab Kings":return "PBKS"
    if teamname == "Lucknow Super Giants":return "LSG"
    if teamname == "Chennai":return "CSK"
    if teamname == "Mumbai":return "MI"
    if teamname == "Bangalore":return "RCB"
    if teamname == "Delhi":return "DC"
    if teamname == "Sunrisers":return "SRH"
    if teamname == "Rajasthan":return "RR"
    if teamname == "Gujarat":return "GT"
    if teamname == "Kolkata":return "KKR"
    if teamname == "Punjab":return "PBKS"
    if teamname == "Lucknow":return "LSG"